# Generated by Django 2.0.13 on 2019-03-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tax_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('is_refundable', models.BooleanField(default=False)),
                ('non_taxable_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.Codes')),
            ],
        ),
        migrations.AddField(
            model_name='bills',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.Items'),
        ),
    ]
